---
# yamllint disable rule:line-length
language: python
install:
  - pip install -r requirements.txt
  - sudo apt-get install openssl
# - ansible-galaxy install -r tests/requirements.yml -p tests/roles

before_script:
  - ansible --version

script:
  - yamllint --strict $(git ls-files '*.yaml' '*.yml')
  - ansible-lint -vvv tests/test.yml
  - ansible-playbook -vvv tests/test.yml -i tests/inventory --syntax-check
  - ansible-playbook -vvv tests/test.yml -i tests/inventory --extra-vars openssl_cert_generate_self_signed_cert=true
