---
- name: Generate a private key
  command: "openssl genrsa -out {{ key_filename }} {{ openssl_cert_key_bits }}"
  args:
    chdir: "{{ openssl_cert_workdir }}"
    creates: "{{ openssl_cert_workdir }}/{{ key_filename }}.stamp"
  vars:
    key_filename: "{{ openssl_cert_common_name }}.key"

- name: Generate a CSR file
  command: "openssl req -new -key {{ key_filename }} -subj '{{ subject }}' -out {{ csr_filename }}"
  args:
    chdir: "{{ openssl_cert_workdir }}"
    creates: "{{ openssl_cert_workdir }}/{{ csr_filename }}.stamp"
  vars:
    key_filename: "{{ openssl_cert_common_name }}.key"
    csr_filename: "{{ openssl_cert_common_name }}.csr"
    subject: "/C={{ openssl_cert_country }}/ST={{ openssl_cert_state }}/O={{ openssl_cert_organization }}/OU={{ openssl_cert_unit }}/CN={{ openssl_cert_common_name }}"

# for self-signed certs:
- name: Generate a self-signed cert and a private key for a custom CA
  command: "openssl req -new -nodes -x509 -days {{ openssl_cert_days }} -subj '{{ subject }}' -keyout {{ key_filename }} -out {{ crt_filename }}"
  args:
    chdir: "{{ openssl_cert_workdir }}"
  vars:
    key_filename: "ca_{{ openssl_cert_common_name }}.key"
    crt_filename: "ca_{{ openssl_cert_common_name }}.crt"
    subject: "/C={{ openssl_cert_country }}/ST={{ openssl_cert_state }}/O={{ openssl_cert_organization }}/OU={{ openssl_cert_unit }}/CN=CA {{ openssl_cert_common_name }}"
  when:
    - openssl_cert_generate_self_signed_cert is defined
    - openssl_cert_generate_self_signed_cert

- name: Generate a self-signed certificate
  command: "openssl x509 -req -days {{ openssl_cert_days }} -CA {{ ca_crt_filename }} -CAkey {{ ca_key_filename }} -CAcreateserial -in {{ csr_filename }} -out {{ crt_filename }}"
  args:
    chdir: "{{ openssl_cert_workdir }}"
    creates: "{{ openssl_cert_workdir }}/{{ crt_filename }}.stamp"
  vars:
    csr_filename: "{{ openssl_cert_common_name }}.csr"
    crt_filename: "{{ openssl_cert_common_name }}.crt"
    ca_key_filename: "ca_{{ openssl_cert_common_name }}.key"
    ca_crt_filename: "ca_{{ openssl_cert_common_name }}.crt"
    subject: "/C={{ openssl_cert_country }}/ST={{ openssl_cert_state }}/O={{ openssl_cert_organization }}/OU={{ openssl_cert_unit }}/CN={{ openssl_cert_common_name }}"
  when:
    - openssl_cert_generate_self_signed_cert is defined
    - openssl_cert_generate_self_signed_cert

# vim:sw=2:ts=2:et:
