---
dependency:
  name: galaxy
driver:
  name: docker
  # TODO
  # name: podman
lint:
  name: yamllint
platforms:
  - name: centos-7
    image: centos:7
    tmpfs:
      - /tmp
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    group_vars:
      all:
        gen_ks_name: centos-7-ks
        gen_ks_rootpw: secret
        gen_ks_outdir: /tmp/ssato.generate_kickstart

scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8

# vim:sw=2:ts=2:et:
